### ISSUE TITLE
[feat] 전체적인 뷰 디자인 변경사항 todo list

### ISSUE THREAD

**Issue by jeongchoyi** [Beer-Itda/Beer-Itda-iOS#153]
- [x] 메인 뷰 bottle shop 찾기 cell
- [x] beer all 뷰 table view cell layout 변경
- [x] beer detail 뷰 상단 layout 변경
- [x] beer detail 뷰 네비바에 하트 아이콘 추가
- [x] beer detail 뷰 review쪽 layout 변경
- [x] review cell 변경
- [x] 로그인 뷰 버튼 cornerRound값 변경
- [x] 마이페이지 뷰 layout 변경
- [x] 등급가이드 뷰 layout 변경
- [x] navigation bar backgroundColor - 투명에서 .white로 변경
